[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.20", features = ["csr"] }
yewdux = "0.9"
stdweb = "0.4.20"
gloo-utils = "0.1.6"
web-sys = "0.3.60"
